// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enum.proto
// Protobuf C++ Version: 6.33.4

#ifndef Enum_2eproto_2epb_2eh
#define Enum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Enum_2eproto;
}  // extern "C"
namespace Protocol {
enum MoveDir : int;
extern const uint32_t MoveDir_internal_data_[];
enum ObjectType : int;
extern const uint32_t ObjectType_internal_data_[];
}  // namespace Protocol
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Protocol::MoveDir_internal_data_>
    internal::EnumTraitsImpl::value<::Protocol::MoveDir>;
template <>
internal::EnumTraitsT<::Protocol::ObjectType_internal_data_>
    internal::EnumTraitsImpl::value<::Protocol::ObjectType>;
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum ObjectType : int {
  PLAYER = 0,
  MONSTER = 1,
  ObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ObjectType_internal_data_[];
inline constexpr ObjectType ObjectType_MIN =
    static_cast<ObjectType>(0);
inline constexpr ObjectType ObjectType_MAX =
    static_cast<ObjectType>(1);
inline bool ObjectType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int ObjectType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ObjectType_descriptor();
template <typename T>
const ::std::string& ObjectType_Name(T value) {
  static_assert(::std::is_same<T, ObjectType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ObjectType_Name().");
  return ObjectType_Name(static_cast<ObjectType>(value));
}
template <>
inline const ::std::string& ObjectType_Name(ObjectType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ObjectType_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool ObjectType_Parse(
    ::absl::string_view name, ObjectType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ObjectType>(ObjectType_descriptor(), name,
                                           value);
}
enum MoveDir : int {
  NONE = 0,
  UP = 1,
  DOWN = 2,
  LEFT = 3,
  RIGHT = 4,
  MoveDir_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  MoveDir_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t MoveDir_internal_data_[];
inline constexpr MoveDir MoveDir_MIN =
    static_cast<MoveDir>(0);
inline constexpr MoveDir MoveDir_MAX =
    static_cast<MoveDir>(4);
inline bool MoveDir_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int MoveDir_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MoveDir_descriptor();
template <typename T>
const ::std::string& MoveDir_Name(T value) {
  static_assert(::std::is_same<T, MoveDir>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to MoveDir_Name().");
  return MoveDir_Name(static_cast<MoveDir>(value));
}
template <>
inline const ::std::string& MoveDir_Name(MoveDir value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MoveDir_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool MoveDir_Parse(
    ::absl::string_view name, MoveDir* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<MoveDir>(MoveDir_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::ObjectType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Protocol::ObjectType>() {
  return ::Protocol::ObjectType_descriptor();
}
template <>
struct is_proto_enum<::Protocol::MoveDir> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Protocol::MoveDir>() {
  return ::Protocol::MoveDir_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Enum_2eproto_2epb_2eh
